"""Per-city tier-1 grid configurations for build_city_grid.py.

Corridors: (label, orientation, parts). Parts are OSM street-name chains
(P) or literal coordinate extensions (PTS); gaps between parts render as
straight connectors (tunnels). Orientation ("ew"/"ns") drives crossing
pairing and terminal naming — for rotated grids assign the closest axis.
"""


def P(names, bbox=None):
    return {"names": names if isinstance(names, list) else [names], "bbox": bbox}


def PTS(points):
    return {"points": points}


CITIES = {
    "sf": {
        "label": "San Francisco",
        "slug": "sf",
        "bbox": (37.703, -122.525, 37.815, -122.350),
        "center_lat": 37.76,
        "corridors": [
            ("Geary",      "ew", [P("Point Lobos Avenue"), P("Geary Boulevard"), P("Geary Street"),
                                  PTS([[-122.3927, 37.7897]])]),
            ("Fulton",     "ew", [P("Fulton Street")]),
            ("Judah",      "ew", [P("Judah Street"), P("Duboce Avenue")]),
            ("Taraval",    "ew", [P("Taraval Street"), P("West Portal Avenue"),
                                  P("Castro Street", (37.760, -122.437, 37.7627, -122.433))]),
            ("Vicente–24th", "ew", [P("Vicente Street"), P("24th Street")]),
            ("Ocean",      "ew", [P("Ocean Avenue"), P("Geneva Avenue")]),
            ("California", "ew", [P("California Street")]),
            ("Union",      "ew", [P("Union Street")]),
            ("Market",     "ew", [P("Portola Drive"), P("Market Street")]),
            ("16th St",    "ew", [P("Parnassus Avenue"), P("16th Street")]),
            ("Sunset",     "ns", [P("Sunset Boulevard"),
                                  P("36th Avenue", (37.771, -122.51, 37.79, -122.49))]),
            ("9th Ave",    "ns", [P("9th Avenue")]),
            ("19th Ave",   "ns", [P("19th Avenue"), P("Park Presidio Boulevard")]),
            ("Masonic",    "ns", [P("Clayton Street"), P("Masonic Avenue"), P("Presidio Avenue")]),
            ("Divisadero", "ns", [P("San Jose Avenue", (37.703, -122.46, 37.742, -122.42)),
                                  P("Castro Street", (37.741, -122.44, 37.769, -122.43)),
                                  P("Divisadero Street")]),
            ("Fillmore",   "ns", [P("Church Street"), P("Fillmore Street")]),
            ("Van Ness",   "ns", [P("South Van Ness Avenue"), P("Van Ness Avenue")]),
            ("Polk",       "ns", [P("Polk Street")]),
            ("Mission",    "ns", [P("Mission Street")]),
            ("Stockton",   "ns", [P("4th Street", (37.768, -122.41, 37.79, -122.39)),
                                  P("Stockton Street")]),
            ("Columbus",   "ns", [P("3rd Street"),
                                  P("Kearny Street", (37.786, -122.4065, 37.7962, -122.4000)),
                                  P("Columbus Avenue")]),
            ("Potrero",    "ns", [P("Bayshore Boulevard", (37.703, -122.42, 37.75, -122.39)),
                                  P("Potrero Avenue"),
                                  P("10th Street", (37.768, -122.42, 37.78, -122.40))]),
            ("Embarcadero", "ns", [P("The Embarcadero")]),
        ],
    },
    "la": {
        "label": "Los Angeles",
        "slug": "la",
        "bbox": (33.900, -118.520, 34.200, -118.150),
        "center_lat": 34.05,
        "corridors": [
            # East–west
            ("Ventura",       "ew", [P("Ventura Boulevard")]),
            ("Victory",       "ew", [P("Victory Boulevard")]),
            ("Sherman Way",   "ew", [P("Sherman Way")]),
            ("Hollywood",     "ew", [P("Hollywood Boulevard")]),
            ("Sunset",        "ew", [P("Sunset Boulevard")]),
            ("Santa Monica",  "ew", [P("Santa Monica Boulevard")]),
            ("Wilshire",      "ew", [P("Wilshire Boulevard")]),
            ("Olympic",       "ew", [P("Olympic Boulevard")]),
            ("Pico",          "ew", [P("Pico Boulevard")]),
            ("Venice",        "ew", [P("Venice Boulevard")]),
            ("Washington",    "ew", [P("Washington Boulevard")]),
            ("MLK",           "ew", [P(["Martin Luther King Jr Boulevard",
                                        "Martin Luther King Jr. Boulevard",
                                        "Martin Luther King Junior Boulevard"])]),
            ("Vernon",        "ew", [P("Vernon Avenue")]),
            ("Manchester",    "ew", [P(["Manchester Avenue", "Manchester Boulevard"])]),
            ("Century",       "ew", [PTS([[-118.4085, 33.9425]]),
                                     P("Century Boulevard", (33.930, -118.408, 33.955, -118.150))]),  # LAX
            ("Slauson",       "ew", [P("Slauson Avenue")]),
            ("Florence",      "ew", [P("Florence Avenue")]),
            ("Whittier",      "ew", [P("Whittier Boulevard")]),
            ("Chavez",        "ew", [P(["Cesar E Chavez Avenue", "Cesar Chavez Avenue",
                                        "West Cesar E Chavez Avenue"])]),
            # North–south
            ("Sepulveda",     "ns", [P("Sepulveda Boulevard")]),
            ("Van Nuys",      "ns", [P("Van Nuys Boulevard")]),
            ("Laurel Canyon", "ns", [P("Laurel Canyon Boulevard")]),
            ("Lankershim",    "ns", [P("Lankershim Boulevard")]),  # NoHo + Universal
            ("Lincoln",       "ns", [P("Lincoln Boulevard")]),
            ("Westwood",      "ns", [P("Westwood Boulevard"), PTS([[-118.4452, 34.0700]])]),  # UCLA
            ("La Cienega",    "ns", [P("La Cienega Boulevard")]),
            ("Fairfax",       "ns", [P("Fairfax Avenue")]),
            ("La Brea",       "ns", [P("La Brea Avenue")]),
            ("Crenshaw",      "ns", [P("Crenshaw Boulevard")]),
            ("Western",       "ns", [P("Western Avenue", (33.900, -118.32, 34.105, -118.30))]),
            ("Normandie",     "ns", [P("Normandie Avenue")]),
            ("Vermont",       "ns", [P("Vermont Avenue")]),
            ("Figueroa",      "ns", [P("Figueroa Street")]),
            ("Broadway",      "ns", [P("Broadway", (33.920, -118.29, 34.062, -118.25))]),
            ("Central",       "ns", [P("Central Avenue", (33.900, -118.27, 34.060, -118.24))]),
            ("Soto",          "ns", [P("Soto Street")]),
            ("Atlantic",      "ns", [P(["Atlantic Boulevard", "Atlantic Avenue"],
                                       (33.900, -118.20, 34.090, -118.15))]),
        ],
    },
    "sandiego": {
        "label": "San Diego",
        "slug": "sandiego",
        "bbox": (32.690, -117.180, 32.780, -117.060),
        "center_lat": 32.73,
        "corridors": [
            ("Broadway",    "ew", [P("Broadway")]),
            ("Market",      "ew", [P("Market Street")]),
            ("University",  "ew", [P("University Avenue")]),
            ("El Cajon",    "ew", [P("El Cajon Boulevard")]),
            ("Adams",       "ew", [P("Adams Avenue")]),
            ("Imperial",    "ew", [P("Imperial Avenue")]),
            ("5th Ave",     "ns", [P("5th Avenue")]),
            ("Park",        "ns", [P("Park Boulevard")]),
            ("30th St",     "ns", [P("30th Street")]),
            ("Fairmount",   "ns", [P("Fairmount Avenue")]),
            ("Euclid",      "ns", [P("Euclid Avenue")]),
        ],
    },
    "sanjose": {
        "label": "San Jose",
        "slug": "sanjose",
        "bbox": (37.260, -122.000, 37.400, -121.820),
        "center_lat": 37.33,
        "corridors": [
            ("Santa Clara", "ew", [P("Santa Clara Street"), P("Alum Rock Avenue")]),
            ("San Carlos",  "ew", [P("Stevens Creek Boulevard"), P("San Carlos Street")]),
            ("Story",       "ew", [P("Story Road")]),
            ("Tully",       "ew", [P("Tully Road")]),
            ("1st St",      "ns", [P("1st Street")]),
            ("Monterey",    "ns", [P("Monterey Road")]),
            ("King",        "ns", [P("King Road")]),
            ("Winchester",  "ns", [P("Winchester Boulevard")]),
            ("Bascom",      "ns", [P("Bascom Avenue")]),
        ],
    },
    "sacramento": {
        "label": "Sacramento",
        "slug": "sacramento",
        "bbox": (38.500, -121.550, 38.650, -121.370),
        "center_lat": 38.57,
        "corridors": [
            ("J St",        "ew", [P("J Street")]),
            ("Broadway",    "ew", [P("Broadway")]),
            ("El Camino",   "ew", [P("El Camino Avenue")]),
            ("16th St",     "ns", [P("16th Street")]),
            ("Franklin",    "ns", [P("Franklin Boulevard")]),
            ("Freeport",    "ns", [P("Freeport Boulevard")]),
            ("Del Paso",    "ns", [P("Del Paso Boulevard")]),
            ("Stockton",    "ns", [P("Stockton Boulevard")]),
        ],
    },
    "fresno": {
        "label": "Fresno",
        "slug": "fresno",
        "bbox": (36.680, -119.900, 36.850, -119.680),
        "center_lat": 36.75,
        "corridors": [
            ("Shaw",        "ew", [P("Shaw Avenue")]),
            ("McKinley",    "ew", [P("McKinley Avenue")]),
            ("Olive",       "ew", [P("Olive Avenue")]),
            ("Kings Canyon", "ew", [P("Ventura Avenue"), P("Kings Canyon Road")]),
            ("Blackstone",  "ns", [P("Blackstone Avenue")]),
            ("Palm",        "ns", [P("Palm Avenue")]),
            ("Cedar",       "ns", [P("Cedar Avenue")]),
            ("First",       "ns", [P("First Street")]),
        ],
    },
    "oc": {
        "label": "Anaheim–Santa Ana",
        "slug": "oc",
        "bbox": (33.700, -117.990, 33.870, -117.790),
        "center_lat": 33.78,
        "corridors": [
            ("Lincoln",     "ew", [P("Lincoln Avenue")]),
            ("Katella",     "ew", [P("Katella Avenue")]),
            ("17th St",     "ew", [P("17th Street")]),
            ("1st St",      "ew", [P("1st Street", (33.735, -117.99, 33.752, -117.80))]),
            ("Harbor",      "ns", [P("Harbor Boulevard")]),
            ("Main",        "ns", [P("Main Street", (33.700, -117.875, 33.790, -117.860))]),
            ("Bristol",     "ns", [P("Bristol Street")]),
            ("State College", "ns", [P("State College Boulevard")]),
        ],
    },
    "longbeach": {
        "label": "Long Beach",
        "slug": "longbeach",
        "bbox": (33.740, -118.220, 33.880, -118.080),
        "center_lat": 33.80,
        "corridors": [
            ("Ocean",       "ew", [P("Ocean Boulevard")]),
            ("7th St",      "ew", [P("7th Street")]),
            ("Anaheim",     "ew", [P("Anaheim Street")]),
            ("Long Beach",  "ns", [P("Long Beach Boulevard")]),
            ("Atlantic",    "ns", [P("Atlantic Avenue")]),
            ("Bellflower",  "ns", [P("Bellflower Boulevard")]),
        ],
    },
    "eastbay": {
        "label": "Oakland–Berkeley",
        "slug": "eastbay",
        "bbox": (37.700, -122.350, 37.905, -122.210),
        "center_lat": 37.80,
        "corridors": [
            ("Shattuck",     "ns", [P("Shattuck Avenue")]),
            ("Telegraph",    "ns", [P("Telegraph Avenue")]),
            ("College",      "ns", [P("College Avenue")]),
            ("San Pablo",    "ns", [P("San Pablo Avenue")]),
            ("MLK",          "ns", [P(["Martin Luther King Jr Way", "Martin Luther King Jr. Way",
                                       "Martin Luther King Junior Way"])]),
            ("Broadway",     "ns", [P("Broadway", (37.790, -122.285, 37.850, -122.235))]),
            ("University",   "ew", [P("University Avenue")]),
            ("Ashby",        "ew", [P("Ashby Avenue")]),
            ("Grand",        "ew", [P("Grand Avenue", (37.795, -122.275, 37.822, -122.230))]),
            ("MacArthur",    "ew", [P("MacArthur Boulevard", (37.760, -122.285, 37.840, -122.210))]),
            ("International", "ew", [P("International Boulevard")]),
        ],
    },
}
